apiVersion: v1
kind: ConfigMap
metadata:
  name: retro-webapp-config
data:
  CENTER_BOX_TITLE: "Retroplay Online by Robert Guske"
  CENTER_BOX_TEXT: "Welcome to Retroplay Online! This is a demo web application running on OpenShift Container Platform. Feel free to explore the platform and check out some of my other projects linked in the navigation bar."
  CENTER_BOX_SUBTEXT: "> This Textbox is adjustable via a Kubernetes Configmap <"
  BG_MODE: "image"
  BG_SOLID: "#0b1020"
  BG_GRAD_FROM: "#0b1020"
  BG_GRAD_TO: "#1b3a6b"
  BG_IMAGE_URL: "https://raw.githubusercontent.com/rguske/jarvislab/main/assets/retroplayonline-logo.png"
  NAV_LINKS_JSON: |
    [
      {"label":"OCP-MK42 WebConsole","url":"https://console-openshift-console.apps.ocp-mk42.retroplay.guske.io/"},
      {"label":"Pacman","url":"https://pacman-pacman.apps.ocp-mk42.retroplay.guske.io/"},
      {"label":"VM CMDB","url":"https://postgresql-read-webapp-postgres.apps.ocp-mk42.retroplay.guske.io"},
      {"label":"Robert @ GitHub","url":"https://github.com/rguske"},
      {"label":"Robert's Blog","url":"https://rguske.github.io"}
    ]
