apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retro-webapp
spec:
  rules:
    - host: retro.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retro-webapp
                port:
                  number: 80